services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
  
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: myuser
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: password
